FROM ruby:3.3

LABEL author="Steve Kenworthy"

ENV HOME /home/app
RUN mkdir -p $HOME
WORKDIR $HOME

ADD . $HOME

RUN apt-get update && \
apt-get install -y imagemagick tzdata default-libmysqlclient-dev mariadb-server mariadb-client libpq-dev && \
apt-get autoremove -y \

RUN cp config/database.mysql.docker.yml config/database.yml

RUN gem install bundler && \
bundle config set --local deployment 'true' && \
bundle install



CMD ["bundle","exec","rails","s"]



EXPOSE 3000